### PR TITLE
Remove Insights event related classes and fix 4.0 compatibility

### PR DESCRIPTION
**Pull request by adejanovski**

### CODE REVIEW

**Review by tjake — CHANGES_REQUESTED** [review]
Thank you!

It would be worth keeping the integration test to verify metrics are being written and filtering works.

**Comment by adejanovski** [comment]
Added back the `EventsIntegrationTest` class which will test various versions of Cassandra and check that metrics are indeed extracted.

**Comment by adejanovski** [comment]
Hi @tjake,
are you happy with the PR?
Let me know if there's anything else to do to get this merged.

Thanks!

**Review by tjake — APPROVED** [review]
Thanks so much!

**Pull request merged**
