### PR TITLE
Alain/merge tlp dashboards

### PR DESCRIPTION
**Pull request by arodrime**
Port the overview dashboard from (`tlp-dashboards`, itself built from `tlp-cluster` dashbaoards).

### CODE REVIEW

**Comment by arodrime** [comment]
@tjake would you check this when you can :). 

A few ideas:

* One thing I would add still in there is the ntp time drift. Not sure how we can capture this metric though, but it matters to get that I think.
* Ultimately, when we have more (themed) dashboards for troubleshooting like read/write path or around sstables management, I would remove a few charts from this one (to make it minimalist and 100% focused on anomaly detection - and not troubleshooting).
* The plan is for this dashboard to replace the `cassandra-condensed` dashboard. For now I'm not removing `cassandra-condensed` though, some people might be using it and we did not speak about this together either.

For now this should already and hopefully help any operator using cassandra.

**Comment by tjake** [comment]
You can enable the ntp plugin in collectd.conf.tmpl 
https://collectd.org/wiki/index.php/Plugin:NTPd

**Comment by tjake** [comment]
Also for consistency, if you could add the logo on the dashboard too

**Comment by arodrime** [comment]
> Also for consistency, if you could add the logo on the dashboard too

Yes sure :). I'll do that 👍 

> I noticed the dashboards are editable by non-logged in users which probably you don't want :)

That's only for the demo if I did things correctly. It was for me to test things in the demo (directly in grafana) before actually putting them in the jsonnet (around metrics/aggregation mostly). If you're happy to have this for the demo only, I'd keep it, if not I can remove it.

> My one ask is you switch the latency charts to use the histogram_percentile() vs min/max/avg from the previous collector limitation.

About percentile, we identified that the more relevant percentile is p99. The min/max/average show actually the worst node, best node and average for the cluster, all actually based on the p99 percentile. I believe showing an average for the cluster of distinct percentiles is somewhat less readable and relevant than knowing about the best/worst nodes using p99.

**Comment by tjake** [comment]
> About percentile, we identified that the more relevant percentile is p99. The min/max/average show actually the worst node, best node and average for the cluster, all actually based on the p99 percentile. I believe showing an average for the cluster of distinct percentiles is somewhat less readable and relevant than knowing about the best/worst nodes using p99.

That's fair but misses the actual SLA if defined at the cluster / dc level.  Perhaps you can add the aggregated P99 to the chart as well?

**Comment by arodrime** [comment]
> > About percentile, we identified that the more relevant percentile is p99. The min/max/average show actually the worst node, best node and average for the cluster, all actually based on the p99 percentile. I believe showing an average for the cluster of distinct percentiles is somewhat less readable and relevant than knowing about the best/worst nodes using p99.
> 
> That's fair but misses the actual SLA if defined at the cluster / dc level. Perhaps you can add the aggregated P99 to the chart as well?

I'm still not clear about that sorry.

What aggregate of p99 are you missing, knowing we already take the min p99, the max p99 and the average p99 of the cluster 🤔? Max gives you the worst nodes p99, min gives the best p99 and isn't avg what you call the 'aggregated p99 for the cluster'? 

I'm not sure if I'm confused with this. It's really non trivial all this aggregate and percentile thinking 😄.

FWIW, queries are as follow:

```
.addTarget(
      prometheus.target(
        expr='max by (cluster, request_type) (' + prefix + '_client_request_latency{cluster=~"$cluster", dc=~"$dc", rack=~"$rack", instance=~"$node", request_type="read", quantile=".99"})',
        legendFormat='max',
      )
    )
    .addTarget(
      prometheus.target(
        expr='min by (cluster, request_type) (' + prefix + '_client_request_latency{cluster=~"$cluster", dc=~"$dc", rack=~"$rack", instance=~"$node", request_type="read", quantile=".99"})',
        legendFormat='min',
      )
    )
    .addTarget(
      prometheus.target(
        expr='avg by (cluster, request_type) (' + prefix + '_client_request_latency{cluster=~"$cluster", dc=~"$dc", rack=~"$rack", instance=~"$node", request_type="read", quantile=".99"})',
        legendFormat='avg',
      )
    )
```

Let me know what I missed. I'll work at adding NTP and the C* logo as mentioned above meanwhile.

**Comment by tjake** [comment]
https://www.circonus.com/2018/11/the-problem-with-percentiles-aggregation-brings-aggravation/

**Comment by tjake** [comment]
http://latencytipoftheday.blogspot.com/2014/06/latencytipoftheday-you-cant-average.html

**Comment by arodrime** [comment]
It took me a while to get back to this, sorry, I've been busy elsewhere.

**Latencies (Percentile debate 🙂)**
Ok, your changes works for me 👍 .

**Tests failing**
There is something wrong in the test, I think it's related with the k8s part, but I'm not sure.

```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

##[error]Process completed with exit code 128.
```

**NTP metrics and Collectd**
I also tried to check for ntp metrics (mostly for the clock drift) here: https://github.com/datastax/metric-collector-for-apache-cassandra/pull/9/files#diff-4f4f46393b7e763b49642c5e432be2a4R92

I don't see the metrics in prometheus. We can also drop it, merge without this and add it later. 

The problem is that I'm not sure how to debug this.
I don't know if I'm missing something in my collectd conf, if there is a place between collectd and prometheus where I need to add a 'allow filter' for these metrics. My feeling is that for some reason the ntp process in instances is not making the metric available, I read we need to use ntp `mode7` and that is isn't the default, I don't know if this can be the problem. But I'm not really used to collectd, nor MCAC yet, I might be missing something obvious.

@tjake do you know what's wrong with the tests and also how to get collectd metrics to prometheus?

**Comment by tjake** [comment]
Thank you!

@bradfordcp will fix the k8 build issue.

**Pull request merged**
