### PR TITLE
improve dashboards according to feedbacks

### PR DESCRIPTION
**Pull request by arodrime**
* Remove NTP settings in collectd (fails with Chrony - default in RHEL...)
* Change stress setting to be able not to overwhelm Cassandra demo nodes (the idea was to see a straight line in terms of requests to fix rates/irates)
* Add mention of supported C* versions to the readme
* Fix Overview dashboards (add missing rate for dropped messages, also change irate --> rate where relevant and the duration/resolution of rates)
* Make dashboards editable
* Update grafonnet-lib docker image to the current latest
* Use UP/DOWN for node status instead of 1/0.

### CODE REVIEW

**Comment by arodrime** [comment]
@tjake would you have a look / possibly merge this when you have a moment? 

Also I can't work on that repo directly yet it seems, no permissions. If that makes sense I'm happy to get admin/committer permissions here :).

**Review by tjake — APPROVED** [review]
Thanks!

What specifically is not working with 4.0? 

We run tests against it https://github.com/datastax/metric-collector-for-apache-cassandra/blob/master/src/test/java/com/datastax/mcac/BaseIntegrationTest.java#L36  did the naming change?

**Comment by arodrime** [comment]
@tjake I can't merge this one, I have no permission here. If it's approved on your side, please go ahead and merge that for me. If there is an issue with this PR, let me know, so I can fix it.

About C*4.0 I'll do the check again tomorrow and let you know more precisely what the problem is so we can fix it, but at a high level, none of the Cassandra metrics was showing up (maybe some renaming indeed, I'm not sure, I'll double check tomorrow)

**Comment by tjake** [comment]
I sent you an invite to this repo a while ago, check https://github.com/datastax/metric-collector-for-apache-cassandra/invitations

**Comment by arodrime** [comment]
oops :( --> "This invitation has expired."

My bad 👎

**Comment by tjake** [comment]
Try again

**Comment by arodrime** [comment]
I'm in 👍, Thanks!

**Pull request merged**
